name: paigun
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.8
  google_maps_flutter_web: ^0.5.0
  map_launcher: ^2.5.0+1
  flutter_polyline_points: ^1.0.0
  place_picker: ^0.10.0
  location: ^4.4.0
  geocoding: ^2.1.0
  supabase_flutter: ^1.10.1
  provider: ^6.0.5
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.6
  pinput: ^2.2.31
  promptpay_qrcode_generate: ^1.0.1
  flutter_rating_bar: ^4.0.1
  flutter_swiper_view: ^1.1.8
  faker: ^2.1.0
  intl: ^0.18.1
  image_picker: ^0.8.7+5
  day_night_time_picker: ^1.2.0+2
  gallery_saver: ^2.3.2
  widgets_to_image: ^0.0.2
  path_provider: ^2.0.5
  snapping_sheet: ^3.1.0
  bottom_sheet_scaffold: ^0.1.6
  google_fonts: ^4.0.4
  intl_phone_field: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/.env
    - assets/images/
    - assets/data/
    - assets/animation/
  uses-material-design: true
